# Generated by Django 5.0.6 on 2024-07-07 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_task_date_added_task_notify'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='task',
            name='notify',
        ),
    ]
